trigger:
  branches:
    include:
      - main

pr: none

variables:
  imageRepository: registry.example.com/industrial-apps/__SERVICE_NAME__
  registryConnection: CHANGE_ME_REGISTRY_SERVICE_CONNECTION

stages:
  - stage: Build
    displayName: Build and publish
    jobs:
      - job: BuildImage
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Login to image registry
            inputs:
              command: login
              containerRegistry: $(registryConnection)

          - script: sh ./docker-build.sh --push $(imageRepository)
            displayName: Build and push version and latest

          - task: Docker@2
            displayName: Logout from image registry
            condition: always()
            inputs:
              command: logout
              containerRegistry: $(registryConnection)
